spring:
  cloud:
    gateway:
      routes:
        - id: sport-venue-management-service
          uri: lb://SPORT-VENUE-MANAGEMENT-SERVICE
          predicates:
            - Path=/welcome
        - id: user-authenticate
          uri: lb://USER-AUTHENTICATE
          predicates:
            - Path=/hello
  application:
    name: CLOUD-API-GATEWAY


server:
  port: 2222

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true

