spring:
  application:
    name: user_authenticate
  boot:
    admin:
      client:
        url: http://localhost:1111/


server:
  port: 8081

#axpose all actuators endpoints
management:
  endpoints:
    web:
      exposure:
        include: '*'
