spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/kbaduwal/Microservice/tree/346a1b3dd5b53c9e889d84591ec961b130178866/configuration_properties
          clone-on-start: true