spring:
  application:
    name: sport-venue-management-service
  boot:
    admin:
      client:
        url: http://localhost:1111/
  datasource:
    username: root
    password: KMPmoto@2024
    url: jdbc:mysql://localhost:3306/KJSVM
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 9091

management:
  endpoints:
    web:
      exposure:
        include: '*'


  #update --> will update the existing data of the table
  #create --> create new data into table by deleting existing data of the table[delete the table re_create the table]
