spring:
  application:
    name: KJ_Sport_Venue_Management_Service
  boot:
    admin:
      client:
        url: http://localhost:1111/

server:
  port: 9091

management:
  endpoints:
    web:
      exposure:
        include: '*'
